# Use this if you dont need tesseract-ocr
# Use official Python 3.12 slim image
FROM public.ecr.aws/lambda/python:3.12

# Set working directory
WORKDIR /var/task/

# Copy only requirements first for caching dependencies
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app code
COPY . .

# Set the Lambda handler
CMD ["app.worker.lambda_handler"]
