# Use official Python 3.12 slim image
FROM public.ecr.aws/lambda/python:3.12

# Set working directory
WORKDIR /var/task/

# Copy only requirements first for caching dependencies
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app code
COPY . .

# Expose port (for local testing)
EXPOSE 8080

# Run the app with Uvicorn
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
CMD ["app.main.handler"]
